#!/usr/bin/env tsx
/**
 * updateFitRepo.ts
 * ----------------
 * Reads the size-chart PDF from backend/data/size-charts/nuon-size-chart.pdf,
 * extracts all garment styles and measurements, then writes a fresh fitRepository.ts.
 *
 * Usage (from project root):
 *   cd backend && npm run update-fit-repo
 *
 * Or drop a new PDF, rename it to nuon-size-chart.pdf, then run the command above.
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const SCRIPT_DIR = path.join(__dirname);
const PYTHON_SCRIPT = path.join(SCRIPT_DIR, 'extract_pdf_data.py');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'data', 'fitRepository.ts');

function findPythonCommand(): string {
  const candidates = [
    process.env.PYTHON,
    process.env.PYTHON3,
    'python3',
    'python',
    'py -3',
  ].filter(Boolean) as string[];

  for (const candidate of candidates) {
    try {
      execSync(`${candidate} --version`, { stdio: 'ignore' });
      return candidate;
    } catch {
      // continue
    }
  }

  throw new Error('Python executable not found. Set PYTHON/PYTHON3 or install Python (with py launcher).');
}

interface RawMeasurement {
  id: string;
  name: string;
  value: number;
  unit: string;
}

interface RawStyle {
  body: string;
  fit: string;
  reference: string;
  keywords: string[];
  measurements: RawMeasurement[];
}

function generateFitRepositoryTs(styles: RawStyle[]): string {
  const blocks = styles.map(s => {
    const measLines = s.measurements.map(m =>
      `      m('${m.id}', '${m.name.replace(/'/g, "\\'")}', ${m.value}),`
    ).join('\n');

    const kwLines = s.keywords.map(k => `'${k.replace(/'/g, "\\'")}'`).join(', ');

    return `  {
    body: '${s.body}',
    fit: '${s.fit}',
    reference: '${s.reference}',
    keywords: [${kwLines}],
    measurements: [
${measLines}
    ],
  },`;
  }).join('\n');

  return `/**
 * NUON Size Chart — Fit & Sizing Repository
 * AUTO-GENERATED by backend/scripts/updateFitRepo.ts
 * Source: backend/data/size-charts/nuon-size-chart.pdf
 *
 * To regenerate: cd backend && npm run update-fit-repo
 * All values in cm.
 */

export interface FitMeasurement {
  id: string;
  name: string;
  value: number;
  unit: string;
}

export interface FitBlock {
  body: string;
  fit: string;
  reference: string;
  keywords: string[];
  measurements: FitMeasurement[];
}

function m(id: string, name: string, value: number): FitMeasurement {
  return { id, name, value, unit: 'cm' };
}

export const FIT_REPOSITORY: FitBlock[] = [
${blocks}
];
`;
}

async function main() {
  console.log('📄 Reading PDF via Python extractor...');

  const pythonCmd = findPythonCommand();

  let jsonOutput: string;
  try {
    jsonOutput = execSync(`${pythonCmd} "${PYTHON_SCRIPT}"`, { encoding: 'utf8' });
  } catch (err: any) {
    console.error('❌ Python extraction failed:', err.stderr || err.message);
    process.exit(1);
  }

  let styles: RawStyle[];
  try {
    const parsed = JSON.parse(jsonOutput);
    if (parsed.error) {
      console.error('❌ Extractor error:', parsed.error);
      process.exit(1);
    }
    styles = parsed as RawStyle[];
  } catch {
    console.error('❌ Failed to parse extractor output as JSON');
    console.error(jsonOutput.substring(0, 500));
    process.exit(1);
  }

  if (styles.length === 0) {
    console.error('❌ No styles extracted from PDF — check the PDF format');
    process.exit(1);
  }

  console.log(`✅ Extracted ${styles.length} garment styles from PDF:`);
  styles.forEach(s => console.log(`   • ${s.body} (${s.fit}) — ref: ${s.reference} — ${s.measurements.length} measurements`));

  const tsContent = generateFitRepositoryTs(styles);
  fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf8');

  console.log(`\n✅ fitRepository.ts updated → ${OUTPUT_FILE}`);
  console.log('   Restart the backend server to apply changes.');
}

main();
